spring:
  application:
    name: spring security in action
  jpa:
    hibernate:
      ddl-auto: none
    defer-datasource-initialization: true
    database: mysql
    show-sql: true
  sql:
    init:
      mode: always

  data:
    mongodb:
      host: localhost
      port: 27017
      database: spring
      authentication-database: admin
      auto-index-creation: true
      username: root
      password: root123

logging:
  level:
    org.springframework.data.mongodb.core.MongoTemplate: DEBUG




server:
  ssl:
    enabled: true
    key-store: classpath:keystore.jks
    key-store-password: bafang
    key-alias: localhostcert
  port: 8081